//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcuSOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://acumatica.com", ConfigurationName="AcuSOAP.ServiceGateSoap")]
    public interface ServiceGateSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/Process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.GraphObject> ProcessAsync(AcuSOAP.GraphObject Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ProcessBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.GraphObject[]> ProcessBatchAsync(AcuSOAP.GraphObject[] requests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/EnumTables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string[]> EnumTablesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/EnumTablesEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string[]> EnumTablesExAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/EnumGraphs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string[]> EnumGraphsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportEnumNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string[]> ReportEnumNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportEnumTableNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string[]> ReportEnumTableNamesAsync(string fullName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportGetXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> ReportGetXmlAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportGetVersionXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> ReportGetVersionXmlAsync(string name, int ver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task ReportSaveAsync(string name, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportSaveVersionXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task ReportSaveVersionXmlAsync(string name, int ver, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportSaveEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task ReportSaveExAsync(string name, string xml, bool createVersion, string versionDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/ReportGetPreview", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<string> ReportGetPreviewAsync(string xml, int topCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/SetBusinessDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/UploadPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.UploadPackageResponse> UploadPackageAsync(AcuSOAP.UploadPackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/PublishPackages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task PublishPackagesAsync(string[] packageNames, bool mergeWithExistingPackages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/PublishPackagesEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task PublishPackagesExAsync(string[] packageNames, bool mergeWithExistingPackages, AcuSOAP.PublicationOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/CleanupPublish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task CleanupPublishAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/UnpublishAllPackages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task UnpublishAllPackagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/GetPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.GetPackageResponse> GetPackageAsync(AcuSOAP.GetPackageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/LicenseInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.LicenseDetail> LicenseInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/LoginEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.LoginResult> LoginExAsync(string name, string password, string apiVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task<AcuSOAP.LoginResult> LoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://acumatica.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RowServerStub))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(View[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Threading.Tasks.Task LogoutAsync();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GraphServerStub))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public abstract partial class GraphObject
    {
        
        private View[] customViewsField;
        
        private GraphObjectState graphStateField;
        
        private GraphUpdateMode updateModeField;
        
        private PXLongRunStatus processStatusField;
        
        private string logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public View[] CustomViews
        {
            get
            {
                return this.customViewsField;
            }
            set
            {
                this.customViewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GraphObjectState GraphState
        {
            get
            {
                return this.graphStateField;
            }
            set
            {
                this.graphStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GraphUpdateMode UpdateMode
        {
            get
            {
                return this.updateModeField;
            }
            set
            {
                this.updateModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PXLongRunStatus ProcessStatus
        {
            get
            {
                return this.processStatusField;
            }
            set
            {
                this.processStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class View
    {
        
        private int selectActionField;
        
        private int selectStartRowField;
        
        private int selectMaxRowsField;
        
        private int selectTotalRowsField;
        
        private object[] selectParametersField;
        
        private object[] selectSearchesField;
        
        private string[] selectSortColumnsField;
        
        private bool[] selectDescendingsField;
        
        private bool selectDiscardResultsField;
        
        private bool selectNativeRowsField;
        
        private object[] selectRowsField;
        
        private bool insertDiscardResultsField;
        
        private object[] insertRowsField;
        
        private bool updateDiscardResultsField;
        
        private object[] updateRowsField;
        
        private bool deleteDiscardResultsField;
        
        private object[] deleteRowsField;
        
        private WebDialogResult answerField;
        
        private string viewNameField;
        
        private bool queryCacheItemsField;
        
        private object[] cacheItemsField;
        
        private bool queryCacheInsertedField;
        
        private object[] cacheInsertedField;
        
        private bool queryCacheUpdatedField;
        
        private object[] cacheUpdatedField;
        
        private bool queryCacheDeletedField;
        
        private object[] cacheDeletedField;
        
        private bool querySelectAllRecordsField;
        
        private bool querySelectDefaultField;
        
        private bool queryCacheCurrentField;
        
        private object cacheCurrentField;
        
        private bool queryCacheItemsTranslatedField;
        
        private object[] cacheItemsTranslatedField;
        
        private string selectActionNameField;
        
        public View()
        {
            this.deleteDiscardResultsField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SelectAction
        {
            get
            {
                return this.selectActionField;
            }
            set
            {
                this.selectActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SelectStartRow
        {
            get
            {
                return this.selectStartRowField;
            }
            set
            {
                this.selectStartRowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SelectMaxRows
        {
            get
            {
                return this.selectMaxRowsField;
            }
            set
            {
                this.selectMaxRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SelectTotalRows
        {
            get
            {
                return this.selectTotalRowsField;
            }
            set
            {
                this.selectTotalRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public object[] SelectParameters
        {
            get
            {
                return this.selectParametersField;
            }
            set
            {
                this.selectParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public object[] SelectSearches
        {
            get
            {
                return this.selectSearchesField;
            }
            set
            {
                this.selectSearchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] SelectSortColumns
        {
            get
            {
                return this.selectSortColumnsField;
            }
            set
            {
                this.selectSortColumnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public bool[] SelectDescendings
        {
            get
            {
                return this.selectDescendingsField;
            }
            set
            {
                this.selectDescendingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool SelectDiscardResults
        {
            get
            {
                return this.selectDiscardResultsField;
            }
            set
            {
                this.selectDiscardResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool SelectNativeRows
        {
            get
            {
                return this.selectNativeRowsField;
            }
            set
            {
                this.selectNativeRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public object[] SelectRows
        {
            get
            {
                return this.selectRowsField;
            }
            set
            {
                this.selectRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool InsertDiscardResults
        {
            get
            {
                return this.insertDiscardResultsField;
            }
            set
            {
                this.insertDiscardResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public object[] InsertRows
        {
            get
            {
                return this.insertRowsField;
            }
            set
            {
                this.insertRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool UpdateDiscardResults
        {
            get
            {
                return this.updateDiscardResultsField;
            }
            set
            {
                this.updateDiscardResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public object[] UpdateRows
        {
            get
            {
                return this.updateRowsField;
            }
            set
            {
                this.updateRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool DeleteDiscardResults
        {
            get
            {
                return this.deleteDiscardResultsField;
            }
            set
            {
                this.deleteDiscardResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public object[] DeleteRows
        {
            get
            {
                return this.deleteRowsField;
            }
            set
            {
                this.deleteRowsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public WebDialogResult Answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ViewName
        {
            get
            {
                return this.viewNameField;
            }
            set
            {
                this.viewNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool QueryCacheItems
        {
            get
            {
                return this.queryCacheItemsField;
            }
            set
            {
                this.queryCacheItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public object[] CacheItems
        {
            get
            {
                return this.cacheItemsField;
            }
            set
            {
                this.cacheItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool QueryCacheInserted
        {
            get
            {
                return this.queryCacheInsertedField;
            }
            set
            {
                this.queryCacheInsertedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        public object[] CacheInserted
        {
            get
            {
                return this.cacheInsertedField;
            }
            set
            {
                this.cacheInsertedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool QueryCacheUpdated
        {
            get
            {
                return this.queryCacheUpdatedField;
            }
            set
            {
                this.queryCacheUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=24)]
        public object[] CacheUpdated
        {
            get
            {
                return this.cacheUpdatedField;
            }
            set
            {
                this.cacheUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool QueryCacheDeleted
        {
            get
            {
                return this.queryCacheDeletedField;
            }
            set
            {
                this.queryCacheDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public object[] CacheDeleted
        {
            get
            {
                return this.cacheDeletedField;
            }
            set
            {
                this.cacheDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool QuerySelectAllRecords
        {
            get
            {
                return this.querySelectAllRecordsField;
            }
            set
            {
                this.querySelectAllRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool QuerySelectDefault
        {
            get
            {
                return this.querySelectDefaultField;
            }
            set
            {
                this.querySelectDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool QueryCacheCurrent
        {
            get
            {
                return this.queryCacheCurrentField;
            }
            set
            {
                this.queryCacheCurrentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public object CacheCurrent
        {
            get
            {
                return this.cacheCurrentField;
            }
            set
            {
                this.cacheCurrentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool QueryCacheItemsTranslated
        {
            get
            {
                return this.queryCacheItemsTranslatedField;
            }
            set
            {
                this.queryCacheItemsTranslatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=32)]
        public object[] CacheItemsTranslated
        {
            get
            {
                return this.cacheItemsTranslatedField;
            }
            set
            {
                this.cacheItemsTranslatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string SelectActionName
        {
            get
            {
                return this.selectActionNameField;
            }
            set
            {
                this.selectActionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class LoginResult
    {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public enum ErrorCode
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class LicenseRestriction
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class LicenseFeatureInfo
    {
        
        private string idField;
        
        private string nameField;
        
        private bool isEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsEnabled
        {
            get
            {
                return this.isEnabledField;
            }
            set
            {
                this.isEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class LicenseDetail
    {
        
        private string licenseKeyField;
        
        private string licenseTypeField;
        
        private string installationIDField;
        
        private string statusField;
        
        private System.Nullable<System.DateTime> validToField;
        
        private string issuedByField;
        
        private System.Nullable<bool> isPortalField;
        
        private string resourceLevelField;
        
        private LicenseFeatureInfo[] featuresField;
        
        private LicenseRestriction[] restrictionsField;
        
        private LicenseRestriction[] resourceRestrictionsField;
        
        private LicenseRestriction[] featureRestrictionsField;
        
        private LicenseRestriction[] businessRestrictionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LicenseKey
        {
            get
            {
                return this.licenseKeyField;
            }
            set
            {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LicenseType
        {
            get
            {
                return this.licenseTypeField;
            }
            set
            {
                this.licenseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string InstallationID
        {
            get
            {
                return this.installationIDField;
            }
            set
            {
                this.installationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IssuedBy
        {
            get
            {
                return this.issuedByField;
            }
            set
            {
                this.issuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> IsPortal
        {
            get
            {
                return this.isPortalField;
            }
            set
            {
                this.isPortalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ResourceLevel
        {
            get
            {
                return this.resourceLevelField;
            }
            set
            {
                this.resourceLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("feature")]
        public LicenseFeatureInfo[] features
        {
            get
            {
                return this.featuresField;
            }
            set
            {
                this.featuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("restriction")]
        public LicenseRestriction[] restrictions
        {
            get
            {
                return this.restrictionsField;
            }
            set
            {
                this.restrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("restriction")]
        public LicenseRestriction[] resourceRestrictions
        {
            get
            {
                return this.resourceRestrictionsField;
            }
            set
            {
                this.resourceRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("restriction")]
        public LicenseRestriction[] featureRestrictions
        {
            get
            {
                return this.featureRestrictionsField;
            }
            set
            {
                this.featureRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("restriction")]
        public LicenseRestriction[] businessRestrictions
        {
            get
            {
                return this.businessRestrictionsField;
            }
            set
            {
                this.businessRestrictionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class PublicationOptions
    {
        
        private bool allCompaniesField;
        
        private string[] companyListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AllCompanies
        {
            get
            {
                return this.allCompaniesField;
            }
            set
            {
                this.allCompaniesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] CompanyList
        {
            get
            {
                return this.companyListField;
            }
            set
            {
                this.companyListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class RowServerStub
    {
        
        private string classNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public enum WebDialogResult
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Abort,
        
        /// <remarks/>
        Retry,
        
        /// <remarks/>
        Ignore,
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public enum GraphObjectState
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Load,
        
        /// <remarks/>
        Unload,
        
        /// <remarks/>
        LoadUnload,
        
        /// <remarks/>
        Clear,
        
        /// <remarks/>
        ClearUnload,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public enum GraphUpdateMode
    {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        InterfaceFields,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public enum PXLongRunStatus
    {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://acumatica.com")]
    public partial class GraphServerStub : GraphObject
    {
        
        private string classNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPackage", WrapperNamespace="http://acumatica.com", IsWrapped=true)]
    public partial class UploadPackageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://acumatica.com", Order=0)]
        public string packageName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://acumatica.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] packageContents;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://acumatica.com", Order=2)]
        public bool replaceIfPackageExists;
        
        public UploadPackageRequest()
        {
        }
        
        public UploadPackageRequest(string packageName, byte[] packageContents, bool replaceIfPackageExists)
        {
            this.packageName = packageName;
            this.packageContents = packageContents;
            this.replaceIfPackageExists = replaceIfPackageExists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPackageResponse", WrapperNamespace="http://acumatica.com", IsWrapped=true)]
    public partial class UploadPackageResponse
    {
        
        public UploadPackageResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackage", WrapperNamespace="http://acumatica.com", IsWrapped=true)]
    public partial class GetPackageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://acumatica.com", Order=0)]
        public string packageName;
        
        public GetPackageRequest()
        {
        }
        
        public GetPackageRequest(string packageName)
        {
            this.packageName = packageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPackageResponse", WrapperNamespace="http://acumatica.com", IsWrapped=true)]
    public partial class GetPackageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://acumatica.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPackageResult;
        
        public GetPackageResponse()
        {
        }
        
        public GetPackageResponse(byte[] GetPackageResult)
        {
            this.GetPackageResult = GetPackageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceGateSoapChannel : AcuSOAP.ServiceGateSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceGateSoapClient : System.ServiceModel.ClientBase<AcuSOAP.ServiceGateSoap>, AcuSOAP.ServiceGateSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceGateSoapClient() : 
                base(ServiceGateSoapClient.GetDefaultBinding(), ServiceGateSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiceGateSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGateSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceGateSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceGateSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGateSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceGateSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGateSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceGateSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.GraphObject> ProcessAsync(AcuSOAP.GraphObject Request)
        {
            return base.Channel.ProcessAsync(Request);
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.GraphObject[]> ProcessBatchAsync(AcuSOAP.GraphObject[] requests)
        {
            return base.Channel.ProcessBatchAsync(requests);
        }
        
        public System.Threading.Tasks.Task<string[]> EnumTablesAsync()
        {
            return base.Channel.EnumTablesAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> EnumTablesExAsync()
        {
            return base.Channel.EnumTablesExAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> EnumGraphsAsync()
        {
            return base.Channel.EnumGraphsAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> ReportEnumNamesAsync()
        {
            return base.Channel.ReportEnumNamesAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> ReportEnumTableNamesAsync(string fullName)
        {
            return base.Channel.ReportEnumTableNamesAsync(fullName);
        }
        
        public System.Threading.Tasks.Task<string> ReportGetXmlAsync(string name)
        {
            return base.Channel.ReportGetXmlAsync(name);
        }
        
        public System.Threading.Tasks.Task<string> ReportGetVersionXmlAsync(string name, int ver)
        {
            return base.Channel.ReportGetVersionXmlAsync(name, ver);
        }
        
        public System.Threading.Tasks.Task ReportSaveAsync(string name, string xml)
        {
            return base.Channel.ReportSaveAsync(name, xml);
        }
        
        public System.Threading.Tasks.Task ReportSaveVersionXmlAsync(string name, int ver, string xml)
        {
            return base.Channel.ReportSaveVersionXmlAsync(name, ver, xml);
        }
        
        public System.Threading.Tasks.Task ReportSaveExAsync(string name, string xml, bool createVersion, string versionDescription)
        {
            return base.Channel.ReportSaveExAsync(name, xml, createVersion, versionDescription);
        }
        
        public System.Threading.Tasks.Task<string> ReportGetPreviewAsync(string xml, int topCount)
        {
            return base.Channel.ReportGetPreviewAsync(xml, topCount);
        }
        
        public System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date)
        {
            return base.Channel.SetBusinessDateAsync(date);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AcuSOAP.UploadPackageResponse> AcuSOAP.ServiceGateSoap.UploadPackageAsync(AcuSOAP.UploadPackageRequest request)
        {
            return base.Channel.UploadPackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.UploadPackageResponse> UploadPackageAsync(string packageName, byte[] packageContents, bool replaceIfPackageExists)
        {
            AcuSOAP.UploadPackageRequest inValue = new AcuSOAP.UploadPackageRequest();
            inValue.packageName = packageName;
            inValue.packageContents = packageContents;
            inValue.replaceIfPackageExists = replaceIfPackageExists;
            return ((AcuSOAP.ServiceGateSoap)(this)).UploadPackageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task PublishPackagesAsync(string[] packageNames, bool mergeWithExistingPackages)
        {
            return base.Channel.PublishPackagesAsync(packageNames, mergeWithExistingPackages);
        }
        
        public System.Threading.Tasks.Task PublishPackagesExAsync(string[] packageNames, bool mergeWithExistingPackages, AcuSOAP.PublicationOptions options)
        {
            return base.Channel.PublishPackagesExAsync(packageNames, mergeWithExistingPackages, options);
        }
        
        public System.Threading.Tasks.Task CleanupPublishAsync()
        {
            return base.Channel.CleanupPublishAsync();
        }
        
        public System.Threading.Tasks.Task UnpublishAllPackagesAsync()
        {
            return base.Channel.UnpublishAllPackagesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AcuSOAP.GetPackageResponse> AcuSOAP.ServiceGateSoap.GetPackageAsync(AcuSOAP.GetPackageRequest request)
        {
            return base.Channel.GetPackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.GetPackageResponse> GetPackageAsync(string packageName)
        {
            AcuSOAP.GetPackageRequest inValue = new AcuSOAP.GetPackageRequest();
            inValue.packageName = packageName;
            return ((AcuSOAP.ServiceGateSoap)(this)).GetPackageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.LicenseDetail> LicenseInfoAsync()
        {
            return base.Channel.LicenseInfoAsync();
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.LoginResult> LoginExAsync(string name, string password, string apiVersion)
        {
            return base.Channel.LoginExAsync(name, password, apiVersion);
        }
        
        public System.Threading.Tasks.Task<AcuSOAP.LoginResult> LoginAsync(string name, string password)
        {
            return base.Channel.LoginAsync(name, password);
        }
        
        public System.Threading.Tasks.Task LogoutAsync()
        {
            return base.Channel.LogoutAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceGateSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceGateSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/AcuTestUtil/api/ServiceGate.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceGateSoapClient.GetBindingForEndpoint(EndpointConfiguration.ServiceGateSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceGateSoapClient.GetEndpointAddress(EndpointConfiguration.ServiceGateSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceGateSoap,
        }
    }
}
